services:
  postgres:
    image: postgres:latest
    container_name: 'things'
    ports:
      - '5432:5432'
    command: postgres -c max_connections=300
    environment:
      - POSTGRES_DB=${POSTGRES_DB_RST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_RST}
      - POSTGRES_USER=${POSTGRES_USERNAME_RST}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA_RST}
      - TZ=Europe/Kyiv
      - PGTZ=Europe/Kyiv
    volumes:
      - db:/var/lib/postgresql
      - ./mybooks/compose/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./mybooks/.env
    networks:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U things_service -d things_rust" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mybooks:
    build: ./mybooks
    container_name: mybooks
    ports:
      - "8080:8080"
    env_file:
      - ./mybooks/.env
    networks:
      - db
      - internal
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    env_file:
      - ./gateway/.env
    environment:
      - GW_HOST=0.0.0.0
      - GW_PORT=3000
      - GW_CONFIG_PATH=/app/gwconfig.yaml
      - GW_ROUTE_CONFIG_PATH=/app/route_config.yaml
    networks:
      - internal
    depends_on:
      - mybooks

networks:
  db:
    driver: bridge
  internal:
    driver: bridge

volumes:
  db: