use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize,  Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)]
pub enum BookGenre {
    Novel,
    ScienceFiction,
    Fantasy,
    Detective,
    Thriller,
    Adventure,
    HistoricalNovel,
    Biography,
    Memoir,
    PopularScience,
    Philosophy,
    Poetry,
    Drama,
    Comedy,
    Horror,
    ReligiousLiterature,
    Essay,
    ReferenceLiterature,
    ChildrensLiterature,
    HumorAndSatire,
    Folklore,
    Mythology,
    Epic,
    EroticLiterature,
    Journalism,
    PoliticalLiterature,
    EpicFantasy,
    Cyberpunk,
    PostApocalypse,
    AlternativeHistory,
    MagicalRealism,
    SocialFiction,
    ClassicalLiterature,
    ModernLiterature,
    RomanceNovel,
    WarFiction,
    LitRpg,
    HighTechScienceFiction,
    SpaceOpera,
    Steampunk,
    Dystopia,
    Utopia,
    GothicLiterature,
    PoliceNovel,
    SpyNovel,
    HumorousScienceFiction,
    PsychologicalFiction,
    CriticismAndLiteraryCriticism,
    Play,
    It,
}

impl BookGenre {
    pub fn as_rus_str(&self) -> &'static str {
        match self {
            Self::Novel => "Роман",
            Self::ScienceFiction => "Фантастика",
            Self::Fantasy => "Фэнтези",
            Self::Detective => "Детектив",
            Self::Thriller => "Триллер",
            Self::Adventure => "Приключения",
            Self::HistoricalNovel => "Исторический роман",
            Self::Biography => "Биография",
            Self::Memoir => "Мемуары",
            Self::PopularScience => "Научно-популярная литература",
            Self::Philosophy => "Философия",
            Self::Poetry => "Поэзия",
            Self::Drama => "Драма",
            Self::Comedy => "Комедия",
            Self::Horror => "Ужасы",
            Self::ReligiousLiterature => "Религиозная литература",
            Self::Essay => "Эссе",
            Self::ReferenceLiterature => "Справочная литература",
            Self::ChildrensLiterature => "Детская литература",
            Self::HumorAndSatire => "Юмор и сатира",
            Self::Folklore => "Фольклор",
            Self::Mythology => "Мифология",
            Self::Epic => "Эпопея",
            Self::EroticLiterature => "Эротическая литература",
            Self::Journalism => "Публицистика",
            Self::PoliticalLiterature => "Политическая литература",
            Self::EpicFantasy => "Фэнтези-эпик",
            Self::Cyberpunk => "Киберпанк",
            Self::PostApocalypse => "Постапокалипсис",
            Self::AlternativeHistory => "Альтернативная история",
            Self::MagicalRealism => "Магический реализм",
            Self::SocialFiction => "Социальная проза",
            Self::ClassicalLiterature => "Классическая литература",
            Self::ModernLiterature => "Современная литература",
            Self::RomanceNovel => "Любовный роман",
            Self::WarFiction => "Военная проза",
            Self::LitRpg => "ЛитРПГ",
            Self::HighTechScienceFiction => "Хай-тек фантастика",
            Self::SpaceOpera => "Космическая опера",
            Self::Steampunk => "Паропанк стимпанк",
            Self::Dystopia => "Антиутопия",
            Self::Utopia => "Утопия",
            Self::GothicLiterature => "Готическая литература",
            Self::PoliceNovel => "Полицейский роман",
            Self::SpyNovel => "Шпионский роман",
            Self::HumorousScienceFiction => "Юмористическая фантастика",
            Self::PsychologicalFiction => "Психологическая проза",
            Self::CriticismAndLiteraryCriticism => "Критика и литературоведение",
            Self::Play => "Пьеса",
            Self::It => "АйТи",
        }
    }

    pub fn as_en_str(&self) -> &'static str {
            match self {
                Self::Novel => "Novel",
                Self::ScienceFiction => "Science Fiction",
                Self::Fantasy => "Fantasy",
                Self::Detective => "Detective",
                Self::Thriller => "Thriller",
                Self::Adventure => "Adventure",
                Self::HistoricalNovel => "Historical Novel",
                Self::Biography => "Biography",
                Self::Memoir => "Memoir",
                Self::PopularScience => "Popular Science",
                Self::Philosophy => "Philosophy",
                Self::Poetry => "Poetry",
                Self::Drama => "Drama",
                Self::Comedy => "Comedy",
                Self::Horror => "Horror",
                Self::ReligiousLiterature => "Religious Literature",
                Self::Essay => "Essay",
                Self::ReferenceLiterature => "Reference Literature",
                Self::ChildrensLiterature => "Children's Literature",
                Self::HumorAndSatire => "Humor and Satire",
                Self::Folklore => "Folklore",
                Self::Mythology => "Mythology",
                Self::Epic => "Epic",
                Self::EroticLiterature => "Erotic Literature",
                Self::Journalism => "Journalism",
                Self::PoliticalLiterature => "Political Literature",
                Self::EpicFantasy => "Epic Fantasy",
                Self::Cyberpunk => "Cyberpunk",
                Self::PostApocalypse => "Post-Apocalypse",
                Self::AlternativeHistory => "Alternative History",
                Self::MagicalRealism => "Magical Realism",
                Self::SocialFiction => "Social Fiction",
                Self::ClassicalLiterature => "Classical Literature",
                Self::ModernLiterature => "Modern Literature",
                Self::RomanceNovel => "Romance Novel",
                Self::WarFiction => "War Fiction",
                Self::LitRpg => "LitRPG",
                Self::HighTechScienceFiction => "High-Tech Science Fiction",
                Self::SpaceOpera => "Space Opera",
                Self::Steampunk => "Steampunk",
                Self::Dystopia => "Dystopia",
                Self::Utopia => "Utopia",
                Self::GothicLiterature => "Gothic Literature",
                Self::PoliceNovel => "Police Novel",
                Self::SpyNovel => "Spy Novel",
                Self::HumorousScienceFiction => "Humorous Science Fiction",
                Self::PsychologicalFiction => "Psychological Fiction",
                Self::CriticismAndLiteraryCriticism => "Criticism and Literary Criticism",
                Self::Play => "Play",
                Self::It => "IT",
            }
        }
}
